version: '3'

services:
    web:
        container_name: webserver
        build: ./web
        ports:
            - "80:80"
            - "443:443"
        networks:
            app_net:
                ipv4_address: 192.168.1.100
        depends_on:
            - wordpress
        volumes:
            - ./web/default.conf:/etc/nginx/conf.d/default.conf
            - wordpress_data:/var/www/html

    db: 
        container_name: dbserver
        image: mysql:8.0.21
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        env_file: .env-mysql
        environment:
            TZ: "Asia/Tokyo"

        networks:
            app_net:
                ipv4_address: 192.168.1.101
        ports:
            - "3306:3306"
    wordpress:
        container_name: appserver
        image: wordpress:5.5.0-php7.2-fpm-alpine
        volumes:
            - wordpress_data:/var/www/html
            - ./app/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ../themes/FullStackEngineerFromBeginner-theme1:/var/www/html/wp-content/themes/FullStackEngineerFromBeginner-theme1       
        restart: always
        env_file: .env-wordpress
        networks:
            app_net:
                ipv4_address: 192.168.1.102
        depends_on:
            - db
    
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_ARBITRARY: 1
        env_file: .env-phpmyadmin
        networks:
            app_net:
                ipv4_address: 192.168.1.103
        ports:
            - 8081:80
        depends_on:
            - db

networks:
    app_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.0/24
volumes:
    wordpress_data:
    db_data: